### ISSUE TITLE
Добавить перевод по двойному клику ЛКМ

### ISSUE THREAD

**Issue by stkrp** [mdnsk/leo-translate#1]
Привет. Спасибо за дополнение. В оригинальном дополнении была возможность переводить выделенный текст по двойному клику ЛКМ (с доп. клавишей на клавиатуре (Alt, Ctrl) или без).

**Comment by mdnsk** [comment]
Привет. Рад что вам понравилось это дополнение. Я планирую в следующих версиях реализовать вызов окна с переводом как вы описали. Также, нужно сделать страницу настроек дополнения на которой можно настроить, как окно будет вызываться.

**Comment by mdnsk** [comment]
Готово.

**Comment by stkrp** [comment]
@mdnsk, отлично, большое спасибо.
