### ISSUE TITLE
Добавить более выразительные рамки для всплывающего окна перевода

### ISSUE THREAD

**Issue by stkrp** [mdnsk/leo-translate#2]
Сейчас рамки очень тонкие, поэтому содержимое окна перевода сливается со страницей.

### Пример нового оформления

![screenshot-2017-10-5 mdnsk leo-translate](https://user-images.githubusercontent.com/6009743/31225268-ea08963c-a9d9-11e7-9492-42285da4d928.png)

**Comment by mdnsk** [comment]
Добавил внутренний отступ и небольшую тень:
![image](https://user-images.githubusercontent.com/4230254/31936989-88e3ec72-b8f6-11e7-85f2-20ace50ecb35.png)

**Comment by stkrp** [comment]
Не знаю, нужно ли выносить в отдельный тикет, но заметил следующую некритическую проблему.
При переводе текста у правого и/или нижнего края окна браузера, всплывающее окно с переводом не помещается на экране, но появляется горизонтальная прокрутка.

### До
![default](https://user-images.githubusercontent.com/6009743/32170162-9c237798-bd84-11e7-9040-87da5512125a.png)

### После
![default](https://user-images.githubusercontent.com/6009743/32170146-8d544652-bd84-11e7-81c1-4908f16fe109.png)

**Comment by mdnsk** [comment]
@stkrp, я исправил это. В новой версии, окно с переводом больше не выходит за пределы видимой области браузера. Так же, позиция окна больше не зависит от позиции мыши во время клика, а показывается под выделенным слово или над ним.
