### ISSUE TITLE
Не сохраняет контекст для фраз

### ISSUE THREAD

**Issue by feofan-msk** [mdnsk/leo-translate#20]
Если выделить больше одного слова для перевода, то расширение не сохраняет контекст. Понимаю, что это экспериментальная фича, но ее очень не хватает для фразовых глаголов, которые без контекст черт запомнишь

**Comment by mdnsk** [comment]
Здравствуйте!
Когда вы вызываете расширение из контекстного меню, контекст не передаётся.
Вызов из контекстного меню передаёт расширению только выделенное слово, и это позволяет переводить слова на сложных страницах с множеством вложенных фреймах, когда обычный перевод с двойным кликом может не работать.
В будущем, это ограничение будет устранено.
Сейчас вы можете выделять слова двойным кликом, со смещением мыши во время двойного клика. Ещё, можно сразу после двойного клика, зажать shift, стрелками расширить текстовое выделение и нажать на кнопку обновления перевода в верхнем левом углу всплывающего окна с переводом.

**Comment by feofan-msk** [comment]
Действительно, двойной клик со смещением делает именно то, что нужно. Спасибо!
