### ISSUE TITLE
logo for leo-translate

### ISSUE THREAD

**Issue by worlwide** [mdnsk/leo-translate#21]
Hello there. I design a logo in my free time. I want to design a logo for you. What do you think ? I want to contribute you. Do you have an idea ?

**Comment by mdnsk** [comment]
Hello!
That would be great if you improve an existing logo of LeoTranslate.
There are two general requirements, it must be the footprint of a lion and it must be simple, because this icon has very small size in the browser's tab!
Thank you very much!

**Comment by worlwide** [comment]
Could you show the current logotype?

**Comment by mdnsk** [comment]
There are different sizes in this folder: https://github.com/mdnsk/leo-translate/tree/master/extension/icons
