### ISSUE TITLE
Click outside document.body doesn't hide translation popup

### ISSUE THREAD

**Issue by ris58h** [mdnsk/leo-translate#22]
Steps to reproduce:
1. Go to [jug.ru](jug.ru).
2. Select a word for translation and make the popup appear.
3. Click on a side (a white space on the left/right from a content) of the site.

Expected: the popup closes.
Actual: the popup doesn't close.

**Comment by mdnsk** [comment]
Thank you for report!

**Comment by mdnsk** [comment]
@ris58h it is fixed here: https://github.com/mdnsk/leo-translate/commit/51bf86bb50d1d164d0c0a4292f141de6447e9bb8

This bugfix will be included to the next release.

**Comment by mdnsk** [comment]
@ris58h The v1.14.0 has been released. Thank you!
