### ISSUE TITLE
[Bug Report] Popup blinking

### ISSUE THREAD

**Issue by helperman** [mdnsk/leo-translate#24]
Thank you for excellent addon!
It helps me extremely every day and every night :)

But I have noticed an issue: popup blinks before it appears.
My eyes are tired of it miserably.

1. When you hover over any word a popup appears. 
2. Popup size is changing its size few times and it looks like blinking for me and irritates.

**Comment by mdnsk** [comment]
Thank you for bug report!
I think, I will add an option "show popup on load". So with this option enabled, the popup appears only when all translations are loaded.

**Comment by mdnsk** [comment]
Fixed in Leo Translate 1.16.0 :fire:
