### ISSUE TITLE
[Feature Request] Translate multiple words at the same time

### ISSUE THREAD

**Issue by debloc** [mdnsk/leo-translate#26]
Good day!
Now to translate a few words you need to select them and use the context menu.
Can you add futures -> select a few words and double-click (CTRL / ALT / SHIFT) to translate?
Thank you!

**Comment by mdnsk** [comment]
@debloc Hello!
It seems to be a duplicate of #20

**Comment by debloc** [comment]
Thank you for fast request!
Yep, it is what I wanted!
