### ISSUE TITLE
[Feature Request] Translate PDF file

### ISSUE THREAD

**Issue by debloc** [mdnsk/leo-translate#27]
Good day!
Do you may add future translate PDF, now translate does not work on it(it has text layer)
Thank you!

**Comment by mdnsk** [comment]
I think this conversation will help you: https://vk.com/leo_translate?w=wall-159456019_28_r29

**Comment by mdnsk** [comment]
Now, the only way to use add-ons for PDF-files is to open this page: https://mozilla.github.io/pdf.js/web/viewer.html and view your PDF-file there.

This is the related issue in bugzillia: https://bugzilla.mozilla.org/show_bug.cgi?id=1454760
