### ISSUE TITLE
[bug] Автодобавление нескольких слов

### ISSUE THREAD

**Issue by feofan-msk** [mdnsk/leo-translate#29]
После обновления lingualeo API при двойном клике со смещением в словарь стали попадать фразы, даже если я не выбирал для них перевод

**Comment by mdnsk** [comment]
Не получается воспроизвести.
Напиши пожалуйста, какие запросы уходят в тот момент, когда слово добавляется в словарь без выбора перевода.
Вы точно уверены, что слова просто не были добавлены в словарь раньше?

**Comment by feofan-msk** [comment]
Записал видео https://screencast-o-matic.com/watch/cqhqf5ThdY

**Comment by mdnsk** [comment]
Спасибо за видео! У меня тоже воспроизвелось. В оригинальном расширении lingualeo такая же проблема и связано это с ошибкой в API lingualeo.

**Comment by mdnsk** [comment]
Исправлено в LeoTranslate 1.17.1
