### ISSUE TITLE
Добавить контекст для перевода

### ISSUE THREAD

**Issue by mdnsk** [mdnsk/leo-translate#3]
Нужно сделать захват контекста для переводимого слова. Слово, которое добавлено без контекста не попадает в word set "Words from the Internet".

**Comment by mdnsk** [comment]
Implemented.

**Comment by krasnovpro** [comment]
Было бы неплохо переводить контекст и сразу его показывать. Например так:

![1](https://user-images.githubusercontent.com/886676/32695357-6c7c3792-c76a-11e7-9e94-bbbafb4b251b.png)

**Comment by mdnsk** [comment]
@krasnovpro 
Я открыл новую issue по этому предложению https://github.com/mdnsk/leo-translate/issues/6
