### ISSUE TITLE
Target language not found 

### ISSUE THREAD

**Issue by 4815162342lost** [mdnsk/leo-translate#35]
Hello, i have Russian ip, but english version of Firefox.

I do double click to translate from english to russian, but receive an error 'Target language not found'.

Screenshot: https://imgur.com/a/woyitGI

How to fix it?

**Comment by alexva24** [comment]
Eng ver FF not working too

**Comment by mdnsk** [comment]
It seems like lingualeo api has been broken again.
Their official web extension doesn't work too.

**Comment by mdnsk** [comment]
It will be fixed in version 1.17.3.
Now lingualeo disallow getting translations for anonymous users, so extension will work only for authenticated users (you need to login in lingualeo.com, before using the extension)

**Comment by mdnsk** [comment]
fixed
