### ISSUE TITLE
Target language not found

### ISSUE THREAD

**Issue by c269574** [mdnsk/leo-translate#36]
После двойного клика не переводит, вместо этого в pop up пишет:

 Loading...
Target language not found

**Comment by dbmoderro** [comment]
Firefox 69.0.1, тоже самое. Недели три назад работало отлично.

**Comment by mdnsk** [comment]
Разработчики LinguaLeo ограничили доступ к API. Теперь для использования расширения нужно обязательно авторизоваться на сайте lingualeo.com

**Comment by dbmoderro** [comment]
Да, после регистрации стало работать. думаю логично добавить попап сообщение об этом при установке или обновлении расширения.

**Comment by c269574** [comment]
Точно, заработало, спасибо!

**Comment by mdnsk** [comment]
Добавил сообщение об ошибке с предложением авторизоваться на lingualeo.com
