### ISSUE TITLE
An error message received: undefined

### ISSUE THREAD

**Issue by ydakuka** [mdnsk/leo-translate#39]
![https://i.ibb.co/Q99PDbL/Screenshot-from-2020-02-26-01-20-40.png](https://i.ibb.co/Q99PDbL/Screenshot-from-2020-02-26-01-20-40.png)

Последние несколько дней я получаю непонятную ошибку.
```
Mozilla Firefox 73.0 (64-bit)
Ubuntu 18.04.4 LTS
```

**Comment by mdnsk** [comment]
Спасибо! Опубликовал версию 1.17.6. Можно обновиться вручную в менеджере дополнений Firefox.
