### ISSUE TITLE
Сделать перевод с русского на английский и добавить иконку в контекстное меню

### ISSUE THREAD

**Issue by siebentod** [mdnsk/leo-translate#4]
Насколько я помню, в оригинальном аддоне можно было в открывающемся при нажатии на кнопку дополнения окошке писать русские слова и появлялся английский перевод. Можно такое как-нибудь сделать? 
А еще было бы неплохо в контекстном меню картинку какую-нибудь добавить чтобы долго не искать (особенно если это контекстное меню еще какими-то аддонами заполнено).
![734534](https://user-images.githubusercontent.com/33163165/32693138-80d7f5e8-c736-11e7-9740-21ae664fff5a.png)

**Comment by mdnsk** [comment]
Спасибо за пожелания по улучшению дополнения.
В следующих релизах, я сделаю перевод с русского на английский и добавлю иконку в контекстное меню.

**Comment by mdnsk** [comment]
Ваши предложения по улучшению дополнения реализованы в версии 1.5.

**Comment by stkrp** [comment]
https://github.com/mdnsk/leo-translate/commit/414f004689ae5248b642de88905c703545ca02b9#diff-280efef54d1f7d8353f2b3ab8943cc85R87

@mdnsk, можно это же правило использовать в переводе по двойному клику? Только имеет смысл как-то уточнять, что перевод с русского на английский, например, строка не содержит английские буквы, но содержит русские `if (this.input.match(/[A-Za-z]/) === null && this.input.match(/[А-Яа-я]/) !== null) {`.

**P. S.** Интерфейс расширения на английском языке, хотя оно рассчитано на русскоязычную аудиторию.

**Comment by mdnsk** [comment]
@stkrp я планирую в будущем сделать локализацию дополнения на русский язык.
