### ISSUE TITLE
Issue while adding an entry: "An error message received: undefined"

### ISSUE THREAD

**Issue by viznov** [mdnsk/leo-translate#40]
I get the error message while adding words in dictionary.
<a href="https://imgur.com/dPIYZ44"><img src="https://i.imgur.com/dPIYZ44.png" title="source: imgur.com" /></a>

No entry being added to the Lingualeo dictionary at the time.

The next day only one entry for each added word appears in the Lingualeo.

The issue came out in about a month ago.

Firefox 73.0.1

**Comment by mdnsk** [comment]
diplicate #39
