### ISSUE TITLE
Расширение не работает

### ISSUE THREAD

**Issue by carloscondit** [mdnsk/leo-translate#48]
Здравствуйте! Подскажите, пожалуйста, сейчас наблюдаются проблемы в работе расширения? Проверил на двух компьютерах. В chrome расширение от lingualeo работает нормально.
![lingualeo](https://user-images.githubusercontent.com/39201353/87190439-26196600-c2fb-11ea-8d8e-f5d00854d02f.png)

**Comment by mdnsk** [comment]
Исправил это поведение и опубликовал новую версию 1.17.7.

**Comment by carloscondit** [comment]
Спасибо!
