### ISSUE TITLE
Как сделать, чтобы перевод был всегда англ. -> рус., а не брался из языковых настроек браузера?

### ISSUE THREAD

**Issue by tatlem** [mdnsk/leo-translate#49]
Если переключить предпочитаемый язык в настройках Firefox Developer (ver. 80.0b8) на английский, то перевода нет - http://joxi.ru/gmv63dU1qYOGma

**Comment by mdnsk** [comment]
Языковые настройки браузера не влияют на перевод. Возможно, это были какие-то проблемы на стороне lingualeo.
