### ISSUE TITLE
Not compatible with Firefox Quantum

### ISSUE THREAD

**Issue by dzenziur** [mdnsk/leo-translate#5]
Будет ли доступно расширение LinguaLeo в Mozilla Quantum?

**Comment by mdnsk** [comment]
Я проверю, работает ли расширение с Firefox Quantum, и если есть какие-то проблемы, то они будут решены в следующих версиях дополнения.

**Comment by mdnsk** [comment]
@dzenziur проверил на Firefox Quantum 57. Дополнение нормально устанавливается и работает.
