### ISSUE TITLE
Стал глючить, хочу спасти историю, можно ли это сделать как-нибудь?

### ISSUE THREAD

**Issue by VladimirK80** [mdnsk/leo-translate#52]
Раньше я в основном выделял часть фразы и переводил её. 
Заметил, что с какого-то момента дополнение перестало так работать: в том месте, где должен быть перевод на русский, пишет то же самое, что я прошу перевести.
Т.е. текст на английском повторяется 2 раза - в "заголовке" жирным шрифтом, как должно быть, и ниже обычным шрифтом, где место для текста на русском.
Вероятно, это произошло после того, как я в LinguaLeo переключил изучаемый язык с английского на украинский. Переключение обратно не помогло.
Я перешёл на такое же дополнение для Firefox, только официальное, которое недавно выпустил LinguaLeo (оно работало похуже, дольше думало, чем Ваше, поэтому я им не пользовался).
Но моя проблема в следующем. Ваше дополнение в какой-то момент недавно перестало передавать историю переводов в мой словарь в LinguaLeo.
Сейчас я вижу только 10 последних переведённых слов в окне Вашего дополнения.
Можно ли каким-то увидеть больше, чем 10 последних переведённых слов?
Очень буду ждать Вашего ответа.

**Comment by VladimirK80** [comment]
Увидел, что расширение писало слова в Украинский словарь. К сожалению, туда попало ровно 10 слов, то есть те же слова, которые отображаются в истории. Если бы узнать хотя бы 11-е слово из истории, то можно было бы проверить. Если оно есть в Английском словаре, то всё в порядке.

**Comment by mdnsk** [comment]
К сожалению, невозможно узнать какие слова были добавлены ранее. Расширение удаляет старые слова из своей истории, чтобы избежать переполнения хранилища.
