### ISSUE TITLE
An error message received: User not found

### ISSUE THREAD

**Issue by adminsyszg** [mdnsk/leo-translate#58]
When i tried to use adding word to dictonary on any sites, exclude lingualeo.com i had this notification. Re-login had not worked. On lingualeo.com it work perfectly.

**Comment by mdnsk** [comment]
I cannot reproduce this error. Probably there was a problem in lingualeo API.

**Comment by adminsyszg** [comment]
> 
> 
> This may be due to the setting of a "strict" level protection level in firefox privacy settings. Or custom with "all third-party cookies" selected options (or top level - "all cookies"). In this case, extension will not work on sites with a different domain.
> 
> **Solution:** downgrade your settings or add lingualeo to "exceptions" in settings block "cookies and site data"

Yes, it solves my problem
