### ISSUE TITLE
Перевод контекста.

### ISSUE THREAD

**Issue by mdnsk** [mdnsk/leo-translate#6]
Предложение от @krasnovpro

> Было бы неплохо переводить контекст и сразу его показывать. Например так:
> 
> ![1](https://user-images.githubusercontent.com/886676/32695357-6c7c3792-c76a-11e7-9e94-bbbafb4b251b.png)
>

**Comment by mdnsk** [comment]
Реализовано в версии 1.6

**Comment by krasnovpro** [comment]
Нет смысла показывать контекст непереведённым. Ведь непереведённым я его и так вижу на странице.
